/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    workflows: Workflow;
    'workflow-instances': WorkflowInstance;
    'workflow-logs': WorkflowLog;
    blogs: Blog;
    contracts: Contract;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    workflows: WorkflowsSelect<false> | WorkflowsSelect<true>;
    'workflow-instances': WorkflowInstancesSelect<false> | WorkflowInstancesSelect<true>;
    'workflow-logs': WorkflowLogsSelect<false> | WorkflowLogsSelect<true>;
    blogs: BlogsSelect<false> | BlogsSelect<true>;
    contracts: ContractsSelect<false> | ContractsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {};
  globalsSelect: {};
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  roles: ('admin' | 'manager' | 'editor' | 'reviewer')[];
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
}
/**
 * Define reusable workflow templates with multi-stage steps.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflows".
 */
export interface Workflow {
  id: string;
  name: string;
  description?: string | null;
  /**
   * Enter collection slugs (e.g. blogs, contracts). This workflow will attach to these collections dynamically.
   */
  targetCollections: {
    collectionSlug: string;
    id?: string | null;
  }[];
  steps: {
    /**
     * Unique identifier for this step, e.g. "editor-review", "manager-approval"
     */
    stepId: string;
    label: string;
    /**
     * Determines the sequence. Steps are executed in ascending order.
     */
    order: number;
    type: 'approval' | 'review' | 'sign-off' | 'comment-only';
    /**
     * If set, any user with this role can act on this step.
     */
    assignedRole?: ('admin' | 'manager' | 'editor' | 'reviewer') | null;
    /**
     * If set, overrides role — only this user can act on this step.
     */
    assignedUser?: (string | null) | User;
    /**
     * Condition expression to evaluate before activating this step. Supports: >, <, ==, !=, >=, <=. E.g. "amount > 10000" or "status == draft".
     */
    conditions?: string | null;
    /**
     * If set, this step auto-escalates if not completed within this many hours.
     */
    slaHours?: number | null;
    /**
     * Optional: step ID to jump to when this step is approved. Leave blank for sequential flow.
     */
    onApprove?: string | null;
    /**
     * Optional: step ID to jump to when this step is rejected. Leave blank to end workflow on rejection.
     */
    onReject?: string | null;
    id?: string | null;
  }[];
  /**
   * Disable to prevent this workflow from being triggered.
   */
  isActive?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Live workflow state per document.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-instances".
 */
export interface WorkflowInstance {
  id: string;
  workflow: string | Workflow;
  collectionSlug: string;
  documentId: string;
  currentStepId?: string | null;
  currentStepIndex?: number | null;
  status: 'pending' | 'in-progress' | 'completed' | 'rejected' | 'escalated';
  startedAt?: string | null;
  completedAt?: string | null;
  /**
   * Used for SLA calculations.
   */
  stepStartedAt?: string | null;
  triggeredBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Immutable audit trail of all workflow actions.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-logs".
 */
export interface WorkflowLog {
  id: string;
  instance?: (string | null) | WorkflowInstance;
  workflowId: string;
  workflowName?: string | null;
  collectionSlug: string;
  documentId: string;
  stepId: string;
  stepLabel?: string | null;
  actor?: (string | null) | User;
  actorName?: string | null;
  action: 'started' | 'approved' | 'rejected' | 'commented' | 'escalated' | 'completed' | 'skipped';
  comment?: string | null;
  outcome?: string | null;
  timestamp: string;
  /**
   * Extra context captured at the time of the action.
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Blog posts with workflow approval support.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs".
 */
export interface Blog {
  id: string;
  title: string;
  /**
   * URL-friendly identifier (auto-filled from title if left empty).
   */
  slug?: string | null;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  excerpt?: string | null;
  author?: (string | null) | User;
  status?: ('draft' | 'under-review' | 'published' | 'rejected') | null;
  tags?:
    | {
        tag?: string | null;
        id?: string | null;
      }[]
    | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Legal contracts with multi-stage approval workflows.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contracts".
 */
export interface Contract {
  id: string;
  title: string;
  body?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Monetary value — used in workflow conditions (e.g. "amount > 10000").
   */
  amount?: number | null;
  currency?: ('USD' | 'EUR' | 'GBP' | 'INR') | null;
  parties?:
    | {
        name: string;
        role?: string | null;
        email?: string | null;
        id?: string | null;
      }[]
    | null;
  status?: ('draft' | 'under-review' | 'pending-approval' | 'approved' | 'rejected' | 'signed') | null;
  startDate?: string | null;
  endDate?: string | null;
  category?: ('legal' | 'procurement' | 'hr' | 'marketing' | 'technical') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'workflows';
        value: string | Workflow;
      } | null)
    | ({
        relationTo: 'workflow-instances';
        value: string | WorkflowInstance;
      } | null)
    | ({
        relationTo: 'workflow-logs';
        value: string | WorkflowLog;
      } | null)
    | ({
        relationTo: 'blogs';
        value: string | Blog;
      } | null)
    | ({
        relationTo: 'contracts';
        value: string | Contract;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  roles?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflows_select".
 */
export interface WorkflowsSelect<T extends boolean = true> {
  name?: T;
  description?: T;
  targetCollections?:
    | T
    | {
        collectionSlug?: T;
        id?: T;
      };
  steps?:
    | T
    | {
        stepId?: T;
        label?: T;
        order?: T;
        type?: T;
        assignedRole?: T;
        assignedUser?: T;
        conditions?: T;
        slaHours?: T;
        onApprove?: T;
        onReject?: T;
        id?: T;
      };
  isActive?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-instances_select".
 */
export interface WorkflowInstancesSelect<T extends boolean = true> {
  workflow?: T;
  collectionSlug?: T;
  documentId?: T;
  currentStepId?: T;
  currentStepIndex?: T;
  status?: T;
  startedAt?: T;
  completedAt?: T;
  stepStartedAt?: T;
  triggeredBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "workflow-logs_select".
 */
export interface WorkflowLogsSelect<T extends boolean = true> {
  instance?: T;
  workflowId?: T;
  workflowName?: T;
  collectionSlug?: T;
  documentId?: T;
  stepId?: T;
  stepLabel?: T;
  actor?: T;
  actorName?: T;
  action?: T;
  comment?: T;
  outcome?: T;
  timestamp?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blogs_select".
 */
export interface BlogsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  excerpt?: T;
  author?: T;
  status?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contracts_select".
 */
export interface ContractsSelect<T extends boolean = true> {
  title?: T;
  body?: T;
  amount?: T;
  currency?: T;
  parties?:
    | T
    | {
        name?: T;
        role?: T;
        email?: T;
        id?: T;
      };
  status?: T;
  startDate?: T;
  endDate?: T;
  category?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}